#pragma once
#ifndef __GET_TIME_64BIT
#define __GET_TIME_64BIT 1
#endif

#ifndef _FILE_AND_LINE_
#define _FILE_AND_LINE_ __FILE__,__LINE__
#endif


#ifndef MAX_ALLOCA_STACK_ALLOCATION
#define MAX_ALLOCA_STACK_ALLOCATION 1048576
#endif

#ifndef _WIN32_WCE
#define USE_WAIT_FOR_MULTIPLE_EVENTS
#endif

#ifndef _USE_VE_MEMORY_OVERRIDE
#define _USE_VE_MEMORY_OVERRIDE 0
#endif

#ifndef OPEN_SSL_CLIENT_SUPPORT
#define OPEN_SSL_CLIENT_SUPPORT 0
#endif

#ifndef BITSTREAM_STACK_ALLOCATION_SIZE
#define BITSTREAM_STACK_ALLOCATION_SIZE 256
#endif

#ifndef VENET_DEBUG_PRINTF
#define VENET_DEBUG_PRINTF printf
#endif

#ifndef MAXIMUM_NUMBER_OF_INTERNAL_IDS
#define MAXIMUM_NUMBER_OF_INTERNAL_IDS 10
#endif

#ifndef VEAssert

#if defined(_DEBUG)
#define VEAssert(x) assert(x);
#else
#define VEAssert(x) 
#endif

#endif

#ifndef DATAGRAM_MESSAGE_ID_ARRAY_LENGTH
#define DATAGRAM_MESSAGE_ID_ARRAY_LENGTH 512
#endif

#ifndef RESEND_BUFFER_ARRAY_LENGTH
#define RESEND_BUFFER_ARRAY_LENGTH 512
#define RESEND_BUFFER_ARRAY_MASK 511
#endif


#ifndef GET_TIME_SPIKE_LIMIT
#define GET_TIME_SPIKE_LIMIT 0
#endif

#ifndef USE_SLIDING_WINDOW_CONGESTION_CONTROL
#define USE_SLIDING_WINDOW_CONGESTION_CONTROL 1
#endif

#ifndef PREALLOCATE_LARGE_MESSAGES
#define PREALLOCATE_LARGE_MESSAGES 0
#endif

#ifndef VENET_SUPPORT_IPV6
#define VENET_SUPPORT_IPV6 0
#endif

#ifndef VESTRING_TYPE
#if defined(_UNICODE)
#define VESTRING_TYPE VEWString
#define VESTRING_TYPE_IS_UNICODE 1
#else
#define VESTRING_TYPE VEString
#define VESTRING_TYPE_IS_UNICODE 0
#endif
#endif

#ifndef RPC4_GLOBAL_REGISTRATION_MAX_FUNCTIONS
#define RPC4_GLOBAL_REGISTRATION_MAX_FUNCTIONS 32
#endif

#ifndef RPC4_GLOBAL_REGISTRATION_MAX_FUNCTION_NAME_LENGTH
#define RPC4_GLOBAL_REGISTRATION_MAX_FUNCTION_NAME_LENGTH 32
#endif

#ifndef XBOX_BYPASS_SECURITY
#define XBOX_BYPASS_SECURITY 1
#endif

#ifndef BUFFERED_PACKETS_PAGE_SIZE
#define BUFFERED_PACKETS_PAGE_SIZE 8
#endif

#ifndef INTERNAL_PACKET_PAGE_SIZE
#define INTERNAL_PACKET_PAGE_SIZE 8
#endif

#ifndef VEPEER_USER_THREADED
#define VEPEER_USER_THREADED 0
#endif
